<?xml version="1.0"?>
<!DOCTYPE Libros [
        <!ELEMENT Libros (id|titulo|autor|descripcion)*>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT titulo (#PCDATA)>
        <!ELEMENT autor (#PCDATA)>
        <!ELEMENT descripcion (#PCDATA)>
        ]>
<Libros>
    <id> Quijote  </id>
    <titulo>El Quijote</titulo>
    <autor>Cervantes</autor>
    <descripcion>Es el mejor libro de cervantes.</descripcion>
</Libros>